### ISSUE TITLE
Error trying with hindi language .txt file on windows platform

### ISSUE THREAD

**Issue by mxav1111** [MrRettich/MultiTTS#1]
C:\Users\guest\Downloads\MultiTTS-main>python app.py
Traceback (most recent call last):
  File "C:\Users\guest\Downloads\MultiTTS-main\app.py", line 37, in <module>
    main()
  File "C:\Users\guest\Downloads\MultiTTS-main\app.py", line 34, in main
    text_to_speech(txt_file, output_folder, voice)
  File "C:\Users\guest\Downloads\MultiTTS-main\app.py", line 17, in text_to_speech
    text = file.read()
           ^^^^^^^^^^^
  File "C:\Users\guest\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 148: character maps to <undefined>

**Comment by MrRettich** [comment]
This might be because I wrote the program before 11 labs included Hindi, and it used. Multilingual model v1 instead of v2. You can change this in the code by writing the name of the other voice model. I will include it next week if I find the time. cheers!

**Comment by MrRettich** [comment]
ah, yes. Where it says `monolingual_v1` you can replace it in the code with `multilingual_v2`.

**Comment by mxav1111** [comment]
Thank you.
Still same error.
Voice id i am trying to use:- "XVuohJvCGPo2iaul7TvT"  
Also attaching the file for you to experiment with.  
BTW file is utf encoded for hindi. (That's how MS WORD opens it properly, when i choose UTF while opening)
And error shows CP1252  .. so not sure if these are related.
Hopefully this will help sort this out for once.
Thanks for your help.

[Manobal_p1.txt](https://github.com/MrRettich/MultiTTS/files/13552084/Manobal_p1.txt)
